### ISSUE TITLE
mqtt有时候会报错，然后就不会换色了

### ISSUE THREAD

**Issue by aimiku** [TshineZheng/Filamentor#17]
Exception in thread paho-mqtt-client-Filamentor-Bambu-Client:
Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\i\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\i\AppData\Local\Programs\Python\Python312\Lib\site-packages\paho\mqtt\client.py", line 4523, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "C:\Users\i\AppData\Local\Programs\Python\Python312\Lib\site-packages\paho\mqtt\client.py", line 2297, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\i\AppData\Local\Programs\Python\Python312\Lib\site-packages\paho\mqtt\client.py", line 1686, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "C:\Users\i\AppData\Local\Programs\Python\Python312\Lib\site-packages\paho\mqtt\client.py", line 2102, in loop_read
    return self._loop_rc_handle(rc)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\i\AppData\Local\Programs\Python\Python312\Lib\site-packages\paho\mqtt\client.py", line 3047, in _loop_rc_handle
    self._do_on_disconnect(packet_from_broker=False, v1_rc=rc)
  File "C:\Users\i\AppData\Local\Programs\Python\Python312\Lib\site-packages\paho\mqtt\client.py", line 4369, in _do_on_disconnect
    on_disconnect(self, self._userdata, v1_rc)
TypeError: BambuClient.on_disconnect() missing 2 required positional arguments: 'reason_code' and 'properties'

**Comment by TshineZheng** [comment]
@aimiku 不好意思，回复晚了，已处理。
